[phases.setup]
nixPkgs = ["nodejs_20", "chromium", "postgresql"]

[phases.install]
cmds = ["npm install --omit=dev"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "node server.js"

[variables]
CHROME_BIN = "/usr/bin/chromium-browser"
